### PR TITLE
Update peer deps for Next.js to include version 14

### LINKED ISSUE #93: peerDependencies don't include Next.js 14
Next.js 14 is now out so maybe the peerDependencies should be updated as well?

### PR DESCRIPTION
**Pull request by aleehedl**
Fixes #93

### CODE REVIEW

**Comment by jbergstroem** [comment]
There is an open PR that achieves the same: https://github.com/blitz-js/next-superjson-plugin/pull/92

The author states that more work is required.

**Comment by aleehedl** [comment]
More work may be needed, but as far as I know, #92 does not achieve the
same as it does nothing to peerDependencies.

BR,
Alex

**Review by anuj-mulik — APPROVED** [review]

**Review by NiallJoeMaher — APPROVED** [review]

**Review by orionmiz — APPROVED** [review]

**Review by lipis — APPROVED** [review]

**Comment by aleehedl** [comment]
Is there something I can do to make the tests / checks run?

**Comment by orionmiz** [comment]
Published v0.5.10
Thanks for your contribution.

**Pull request merged**
